books_data = [
    {
        "name": "The Great Gatsby",
        "isbn": "9780743273565",
        "publisher": "Scribner",
        "publish_year": "1925-04-10",
        "file_name": "great_gatsby.pdf",
        "times_issued": 100,
        "likes": 500,
        "dislikes": 20,
        "is_flagged": False,
        "file_path": "/path/to/files/great_gatsby.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 180
    },
    {
        "name": "To Kill a Mockingbird",
        "isbn": "9780061120084",
        "publisher": "Harper",
        "publish_year": "1960-07-11",
        "file_name": "to_kill_a_mockingbird.pdf",
        "times_issued": 150,
        "likes": 700,
        "dislikes": 15,
        "is_flagged": False,
        "file_path": "/path/to/files/to_kill_a_mockingbird.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 281
    },
    {
        "name": "1984",
        "isbn": "9780451524935",
        "publisher": "Signet Classics",
        "publish_year": "1949-06-08",
        "file_name": "1984.pdf",
        "times_issued": 200,
        "likes": 900,
        "dislikes": 10,
        "is_flagged": False,
        "file_path": "/path/to/files/1984.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 328
    },
    {
        "name": "The Catcher in the Rye",
        "isbn": "9780316769488",
        "publisher": "Back Bay Books",
        "publish_year": "1951-07-16",
        "file_name": "catcher_in_the_rye.pdf",
        "times_issued": 180,
        "likes": 800,
        "dislikes": 25,
        "is_flagged": False,
        "file_path": "/path/to/files/catcher_in_the_rye.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 277
    },
    {
        "name": "Moby-Dick",
        "isbn": "9781853260087",
        "publisher": "Wordsworth Editions",
        "publish_year": "1851-10-18",
        "file_name": "moby_dick.pdf",
        "times_issued": 120,
        "likes": 600,
        "dislikes": 30,
        "is_flagged": False,
        "file_path": "/path/to/files/moby_dick.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 720
    },
    {
        "name": "Pride and Prejudice",
        "isbn": "9780141439518",
        "publisher": "Penguin Classics",
        "publish_year": "1813-01-28",
        "file_name": "pride_and_prejudice.pdf",
        "times_issued": 250,
        "likes": 1000,
        "dislikes": 5,
        "is_flagged": False,
        "file_path": "/path/to/files/pride_and_prejudice.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 480
    },
    {
        "name": "The Lord of the Rings",
        "isbn": "9780618640157",
        "publisher": "Mariner Books",
        "publish_year": "1954-07-29",
        "file_name": "lord_of_the_rings.pdf",
        "times_issued": 300,
        "likes": 1200,
        "dislikes": 40,
        "is_flagged": False,
        "file_path": "/path/to/files/lord_of_the_rings.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 1178
    },
    {
        "name": "The Hobbit",
        "isbn": "9780345339683",
        "publisher": "Del Rey",
        "publish_year": "1937-09-21",
        "file_name": "the_hobbit.pdf",
        "times_issued": 270,
        "likes": 1100,
        "dislikes": 35,
        "is_flagged": False,
        "file_path": "/path/to/files/the_hobbit.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 310
    },
    {
        "name": "War and Peace",
        "isbn": "9781400079988",
        "publisher": "Vintage Classics",
        "publish_year": "1869-01-01",
        "file_name": "war_and_peace.pdf",
        "times_issued": 140,
        "likes": 750,
        "dislikes": 20,
        "is_flagged": False,
        "file_path": "/path/to/files/war_and_peace.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 1392
    },
    {
        "name": "Crime and Punishment",
        "isbn": "9780679734505",
        "publisher": "Vintage",
        "publish_year": "1866-11-14",
        "file_name": "crime_and_punishment.pdf",
        "times_issued": 160,
        "likes": 850,
        "dislikes": 15,
        "is_flagged": False,
        "file_path": "/path/to/files/crime_and_punishment.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 576
    },
    {
        "name": "The Great Expectations",
        "isbn": "9780141439563",
        "publisher": "Penguin Classics",
        "publish_year": "1861-12-01",
        "file_name": "great_expectations.pdf",
        "times_issued": 190,
        "likes": 950,
        "dislikes": 10,
        "is_flagged": False,
        "file_path": "/path/to/files/great_expectations.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 544
    },
    {
        "name": "One Hundred Years of Solitude",
        "isbn": "9780060883287",
        "publisher": "Harper Perennial Modern Classics",
        "publish_year": "1967-05-30",
        "file_name": "one_hundred_years_of_solitude.pdf",
        "times_issued": 220,
        "likes": 850,
        "dislikes": 25,
        "is_flagged": False,
        "file_path": "/path/to/files/one_hundred_years_of_solitude.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 417
    },
    {
        "name": "Don Quixote",
        "isbn": "9780060934347",
        "publisher": "Harper Perennial Modern Classics",
        "publish_year": "1605-01-16",
        "file_name": "don_quixote.pdf",
        "times_issued": 130,
        "likes": 700,
        "dislikes": 30,
        "is_flagged": False,
        "file_path": "/path/to/files/don_quixote.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 1023
    },
    {
        "name": "The Odyssey",
        "isbn": "9780140268867",
        "publisher": "Penguin Classics",
        "publish_year": "800 BCE",
        "file_name": "the_odyssey.pdf",
        "times_issued": 110,
        "likes": 600,
        "dislikes": 20,
        "is_flagged": False,
        "file_path": "/path/to/files/the_odyssey.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 416
    },
    {
        "name": "Anna Karenina",
        "isbn": "9780143035008",
        "publisher": "Penguin Classics",
        "publish_year": "1877-01-01",
        "file_name": "anna_karenina.pdf",
        "times_issued": 170,
        "likes": 800,
        "dislikes": 15,
        "is_flagged": False,
        "file_path": "/path/to/files/anna_karenina.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 864
    },
    {
        "name": "Frankenstein",
        "isbn": "9780141439471",
        "publisher": "Penguin Classics",
        "publish_year": "1818-01-01",
        "file_name": "frankenstein.pdf",
        "times_issued": 150,
        "likes": 700,
        "dislikes": 30,
        "is_flagged": False,
        "file_path": "/path/to/files/frankenstein.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 352
    },
    {
        "name": "The Brothers Karamazov",
        "isbn": "9780140449242",
        "publisher": "Penguin Classics",
        "publish_year": "1880-11-26",
        "file_name": "the_brothers_karamazov.pdf",
        "times_issued": 140,
        "likes": 750,
        "dislikes": 20,
        "is_flagged": False,
        "file_path": "/path/to/files/the_brothers_karamazov.pdf",
        "number_of_volumes": 1,
        "number_of_pages": 796
    }
]
